version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:16.5.0-ee.0'
    container_name: 'gitlab-server'
    restart: always
    ports:
      - '2202:22'
      - '80:80'
      - '443:443'
    volumes:
      - '/home/utadmin/gitlab_test/testvol/config:/etc/gitlab'
      - '/home/utadmin/gitlab_test/testvol/logs:/var/log/gitlab'
      - '/home/utadmin/gitlab_test/testvol/data:/var/opt/gitlab'
    shm_size: '256m'
